FROM node:20-alpine AS base

FROM base AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat python3 make g++
RUN npm install -g turbo
COPY . .
RUN turbo prune @chorus/web --docker

FROM base AS installer
RUN apk add --no-cache libc6-compat python3 make g++
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm ci
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
COPY tsconfig.base.json tsconfig.base.json
RUN npx turbo run build --filter=@chorus/web...

FROM base AS runner
WORKDIR /app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

# Automatically leverage output traces to reduce image size using the standalone output behavior
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static

# Note: The standalone build puts the server.js file correctly alongside other node_modules relative to the monorepo path
EXPOSE 3000
CMD ["node", "apps/web/server.js"]
